spring:
  config:
    name: ${spring.application.name}
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ssZ
    #timeZone: America/Bogota
    timeZone: America/Mexico_City

server:
  port: 10400
  servlet:
    contextPath: /ms365/configserver
  
logging:
  level:
    root: INFO
  pattern:
    console: "${spring.application.name} > %-5p : %40.40c{1}[%20.20M:%4L] - %m%n"
  
management:
  security:
    enabled: false
  endpoint:
    health:
      showDetails: always
    shutdown:
      enabled: true
    restart:
      enabled: true
  endpoints:
    web: 
      basePath: /server
      exposure:
        include: "*"
  server:
    port: 20400
    servlet:
      contextPath: /admin

info:
  name: Spring Cloud 365 Config-Server     
  runtime:
    project:
      version: @runtime.project.version@
      artifact: @runtime.project.artifact@  
    environment:
      name: @runtime.env.name@
      profile: @runtime.env.profile@
      folders:
        config: @runtime.env.folder.config@ 
      
---
spring:
  config:
    activate:
      onProfile: native
info:
  title: Spring Cloud Config-Server [FileSystem] !!!
  location: filesystem  
            
---
spring:
  config:
    activate:
      onProfile: cloud
info:
  title: Spring Cloud Config-Server [Cloud] !!!
  location: cloud  
    
