spring:
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/ms365_usuario?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:

    
