spring:
  config:
    name: ${spring.application.name}
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    
server:
  port: 10430

management:
  server:
    port: 20430  

eureka:
#  instance:
#    appname: ${spring.config.name}
  client:
    registerWithEureka: true
    fetchRegistry: true
                  
application:
  folder:
    proyectos: ./proyectos

info:
  name: Spring Cloud 365 MS-Proyectos-Archivos     
  runtime:
    project:
      version: @runtime.project.version@
      artifact: @runtime.project.artifact@  
    environment:
      name: @runtime.env.name@
      profile: @runtime.env.profile@
      hosts:
        config: @runtime.env.hosts.config@ 
        eureka: @runtime.env.hosts.eureka@  

